version: '3'
services:
  e2e:
    image: e2e:latest # build your own image
    
    # enable tty and stdin to make `docker attach` work
    tty: true
    stdin_open: true

    cap_drop:
      - ALL

    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    restart: unless-stopped

    # map config to host machine
    volumes:
      - ./world:/app/world
      - ./server.properties:/app/server.properties
      - ./whitelist.json:/app/server.properties
      - ./ops.json:/app/ops.json
